# model checkpoint name meaning: 
# f"{MODEL_NAME}_{LR}_{BATCH_SIZE}_{LATENT_SIZE}_{BETA}.pth"
MODEL:
  TYPE: "CGAN"
  NAME: "resnet_CGAN_2p_var3_pr_512" # base name used to save the model
  CHECKPOINT_FOLDER: "./CGAN/checkpoints"
  ARCHITECTURE_YAML_NAME: resnet_gan.yaml
  RESUME_FROM_CHECKPOINT: True

TRAINING:
  NUM_EPOCHS: 1000
  BATCH_SIZE: 256
  NUM_WORKERS: 10
  LABEL_SMOOTHING: 0.1
  WITH_AUGMENTATION: False # aug
  GENERATOR:
    LR: 0.0001 # 1e-5
  DISCRIMINATOR: 
    LR: 0.000001 # 1e-6


TEST_ONLY: False

DATASET_PATH: "/home/pfoggia/GenerativeAI/CELEBA/" # DATASET PATH

OUTPUT_PATH: "CGAN/Results"
