# model checkpoint name meaning: 
# f"{MODEL_NAME}_{LR}_{BATCH_SIZE}_{LATENT_SIZE}_{BETA}.pth"
MODEL:
  TYPE: "VAE"
  NAME: "res_VAE" # base name used to save the model
  CHECKPOINT_FOLDER: "./CVAE/checkpoints"
  ARCHITECTURE_YAML_NAME: res_VAE.yaml
  RESUME_FROM_CHECKPOINT: True

TRAINING:
  NUM_EPOCHS: 1000
  LR: 0.001 # 1e-3
  BATCH_SIZE: 128
  NUM_WORKERS: 10
  BETA: 1.0 # beta for VAE loss

  WITH_AUGMENTATION: False # aug

  TEST_ONLY: False

DATASET_PATH: "/mnt/datasets/eeg/celeba/" # MATTIA DATASET PATH

OUTPUT_PATH: "CVAE/Results"
