# model checkpoint name meaning: 
# f"{MODEL_NAME}_{LR}_{BATCH_SIZE}_{LATENT_SIZE}_{BETA}.pth"
MODEL:
  TYPE: "DModel" # Model type
  NAME: "baseline" # base name used to save the model
  CHECKPOINT_FOLDER: "./GUIDED-DIFFUSION/checkpoints"
  ARCHITECTURE_YAML_NAME: baseline.yaml
  RESUME_FROM_CHECKPOINT: True

TRAINING:
  BATCH_SIZE: 128
  NUM_EPOCHS: 100
  LR: 0.001 # 1e-3
  L: 1000
  COND_SHAPE: [8] # vecotor with 1 for each condition (barba, occhiali, genere)
  NUM_WORKERS: 10

  WITH_AUGMENTATION: False # aug

TEST_ONLY: False

DATASET_PATH: "/localstorage/mmarseglia/" # DATASET PATH

OUTPUT_PATH: "GUIDED-DIFFUSION/Results"